//购物车控制层
app.controller('cartController',function($http,$scope,cartService,loginService){
    //查询购物车列表
    $scope.findCartList=function(){
        cartService.findCartList().success(
            function(response){
                $scope.cartList=response;
                $scope.totalValue=cartService.sum($scope.cartList);//求合计数
            }
        );
    }
    //添加商品到购物车
    $scope.addGoodsToCartList=function(itemId,num){
        cartService.addGoodsToCartList(itemId,num).success(
            function(response){
                if(response.success){
                    $scope.findCartList();//刷新列表
                }else{
                    alert(response.message);//弹出错误提示
                }
            }
        );
    }
    $scope.showName=function(){
        var c= $http.get('http://localhost:9106/login/name.do',{'withCredentials':true});
        $http.get('http://localhost:9106/login/name.do',{'withCredentials':true}).success(
            function(response){
                $scope.loginName=response.loginName;
                alert(loginName)
            }
        );
    }
});
